name = "github-auth"
type = "javascript"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-12-28"

kv_namespaces = [
  { binding = "SESSION", id = "" },
  { binding = "STATE", id = "" },
]

[vars]
GITHUB_CLIENT_ID = "<your github client id>"
GITHUB_CLIENT_SECRET = "<your github client secret>"
GITHUB_REDIRECT_URI="http://localhost:8787/signin/callback"

[build]
command = "yarn && yarn build"
[build.upload]
format = "service-worker"
